---
# Docker compose manifest to run a compatible database
# for the FinWar project.
name: finwar

services:
  timescaledb:
    image: docker.io/timescale/timescaledb:2.22.0-pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-finwar}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-finwar}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finwar"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: ./servers/rust-server
      dockerfile: docker/Dockerfile
    environment:
      FINWAR_MARKET_DATABASE_URL: postgresql://${POSTGRES_USER:-finwar}:${POSTGRES_PASSWORD:-password}@timescaledb:5432/${POSTGRES_DB:-finwar}
      RUST_LOG: info
    command: migrate
    depends_on:
      timescaledb:
        condition: service_healthy

  rust-server:
    build:
      context: ./servers/rust-server
      dockerfile: docker/Dockerfile
    ports:
      - "4444:4444"
    environment:
      FINWAR_MARKET_DATABASE_URL: postgresql://${POSTGRES_USER:-finwar}:${POSTGRES_PASSWORD:-password}@timescaledb:5432/${POSTGRES_DB:-finwar}
      FINWAR_MARKET_TARGET_TICKER: NVDA
      RUST_LOG: info
    command: serve
    depends_on:
      migration:
        condition: service_completed_successfully

  rust-server-healthchecker:
    image: docker.io/library/busybox:stable-uclibc
    command: ["sh", "-c", "tail -f /dev/null"]
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --tries=1 http://rust-server:4444/api/time || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      - rust-server

  rando-bot:
    build:
      context: ./bots/rando
      dockerfile: docker/Dockerfile
    environment:
      FINWAR_MARKET_API_ENDPOINT: http://rust-server:4444
    restart: unless-stopped
    depends_on:
      rust-server-healthchecker:
        condition: service_healthy

volumes:
  db_data:
