---
# Docker compose manifest to run a compatible database
# for the FinWar project.
name: finwar

services:
  timescaledb:
    image: docker.io/timescale/timescaledb:2.22.0-pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-finwar}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-finwar}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finwar"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: ./servers/rust-server
      dockerfile: docker/Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-finwar}:${POSTGRES_PASSWORD:-password}@timescaledb:5432/${POSTGRES_DB:-finwar}
      RUST_LOG: info
    command: migrate
    depends_on:
      timescaledb:
        condition: service_healthy

  rust-server:
    build:
      context: ./servers/rust-server
      dockerfile: docker/Dockerfile
    ports:
      - "4444:4444"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-finwar}:${POSTGRES_PASSWORD:-password}@timescaledb:5432/${POSTGRES_DB:-finwar}
      RUST_LOG: info
    command: serve
    depends_on:
      migration:
        condition: service_completed_successfully

  random-bot:
    image: python:3.12-slim
    restart: unless-stopped
    depends_on:
      - rust-server
    volumes:
      - ./bots:/app
    working_dir: /app
    command: sh -c "pip install requests && python bot_random.py"
    environment:
      API_URL: http://rust-server:4444

volumes:
  db_data:
