---
name: Market API Release

permissions:
  packages: write
  contents: read

on:
  push:
    tags:
      - 'market-api-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - id: get-version
        run: echo "version=${GITHUB_REF#refs/tags/market-api-v}" >> $GITHUB_OUTPUT

  build-push-container:
    needs: extract-version
    uses: ./.github/workflows/container_build_push.yaml
    with:
      context: servers/rust-server
      image_name: market-api
      version: ${{ needs.extract-version.outputs.version }}
      ref: ${{ github.sha }}
